### PR TITLE
[WIP] Issue/fix skip instrumental

### LINKED ISSUE #254: Skip instrumental message will be displayed wrong in duet songs
### Actual behaviour

If you play a duet song and the second singer is singing, but the lead singer has nothing to sing currently, the "skip instrumental" message will be displayed in the top right.

### Expected behaviour

As long as one of the two singers have a text to sing, don't show this "skip instrumental" message.

### Details

Provide some additional information:

- performous version: 1.1
- operating system + version: Windows 10 x64

### PR DESCRIPTION
**Pull request by Lord-Kamina**
Discussion of background for this in #254 

# Issues
* Closes #254

### CODE REVIEW

File: game/song.cc [hunk 1]
```diff
@@ -70,18 +70,19 @@ namespace {
...
-		Notes s2 = getVocalTrack(1).notes;
-		Notes notes;
+		s1 = getVocalTrack(0).notes;
+		s2 = getVocalTrack(1).notes;
 		std::merge(s1.begin(), s1.end(), s2.begin(), s2.end(), std::back_inserter(notes), Note::ltBegin);
 		it = std::lower_bound(notes.begin(), notes.end(), target, noteEndLessThan);
 	}
 	else {
+		notes = getVocalTrack().notes;
 		it = std::lower_bound(getVocalTrack().notes.begin(), getVocalTrack().notes.end(),target, noteEndLessThan);
```
Comment (Baklap4) [inline game/song.cc]: line 83 can be shortned with `it = std::lower_bound(notes.begin(), notes.end(),target, noteEndLessThan);`

Comment (Lord-Kamina) [reply game/song.cc]: That's what I meant to write but it was late and I was tired and kinda frustrated. :P

Comment (Baklap4) [reply game/song.cc]: Does it already fixes this issue? if so i'll check it later tonight

Comment (Lord-Kamina) [reply game/song.cc]: Kinda but it's far from being a complete solution, ergo why it's still [WIP]

File: game/menu.cc [hunk 2]
```diff
@@ -39,7 +44,7 @@ void Menu::move(int dir) {
 	else if (dir < 0 && selection_stack.back() > 0) --selection_stack.back();
 }
 
-void Menu::select(unsigned sel) {
+void Menu::select(size_t sel) {
```
Comment (nieknooijens) [inline game/menu.cc]: why a size_t? (uint32_t) sel is the "current selection" it doesn't represent a size of some sort.

File: game/screen_sing.cc [hunk 3]
```diff
@@ -40,6 +40,11 @@ ScreenSing::ScreenSing(std::string const& name, Audio& audio, Database& database
 	m_selectedTrack(TrackName::LEAD_VOCAL)
 {}
 
+bool ScreenSing::singingDuet() {
```
Comment (nieknooijens) [inline game/screen_sing.cc]: this renders this function completely useless, so unless you're going to add the comparison back in in a later stage and only commented it for debugging, I suggest removing the function entirely to get rid of clutter.

File: game/screen_sing.cc [hunk 4]
```diff
@@ -40,6 +40,11 @@ ScreenSing::ScreenSing(std::string const& name, Audio& audio, Database& database
...
+return false;
+// 	return (m_song.hasDuet() && m_duet == 0 && )
+}
+
 void ScreenSing::enter() {
 	keyPressed = false;
 	m_DuetTimeout.setValue(10);
```
Comment (Baklap4) [inline game/screen_sing.cc]: Duet timeout should be configurable from config

File: game/menu.cc (hunk 2 above)
Comment (Lord-Kamina) [reply game/menu.cc]: Because it is compared against a size()

File: game/screen_sing.cc (hunk 3 above)
Comment (Lord-Kamina) [reply game/screen_sing.cc]: I am. That's the whole point of [WIP]

File: game/screen_sing.cc (hunk 4 above)
Comment (Lord-Kamina) [reply game/screen_sing.cc]: What is that timeout even doing? Either way, that magic number was already there. Not my addition.

Comment (Baklap4) [reply game/screen_sing.cc]: The timeout is there for autoplaying the song if no keyboard is pressed for 10 secs it's autoplaying with the suggested playersetting if i'm right.

**Comment by Lord-Kamina** [comment]
I'm done with this now.

File: game/screen_sing.hh [hunk 5]
```diff
@@ -103,6 +104,9 @@ class ScreenSing: public Screen {
 	std::string m_selectedTrackLocalized;
 	ConfigItem m_vocalTracks[AUDIO_MAX_ANALYZERS];
 	ConfigItem m_duet;
+	size_t players() const { 	boost::ptr_vector<Analyzer>& analyzers = m_audio.analyzers(); return (analyzers.empty() ? 1 : analyzers.size()); } // Always have at least one player to display lyrics and prevent crashes.
```
Comment (Baklap4) [inline game/screen_sing.hh]: hmm `boost::ptr_vector<T>` can be, and imho should be, `std::vector<std::unique_ptr<T>`. However this would also mean `m_audio.analyzers()` return type need to be `std::vector<std::unique_ptr<T>`

Comment (Lord-Kamina) [reply game/screen_sing.hh]: That's an enhancement, I guess? I just refactored what was already there.

Comment (Baklap4) [reply game/screen_sing.hh]: Agreed therefore not blocking it

File: game/menu.cc [hunk 6]
```diff
@@ -15,6 +15,11 @@ std::string MenuOption::getName() const {
 	return "";
 }
 
+std::string MenuOption::getVirtName() const {
+	if (!virtualName.empty()) return virtualName;
```
Comment (Baklap4) [inline game/menu.cc]: Can be made into a single return statement:
`return !virtualName.empty() ? virtualName : std::string();`

File: game/screen_sing.hh (hunk 5 above)
Comment (Lord-Kamina) [reply game/screen_sing.hh]: BTW, what with this branch and the search one adding several new config items... I'm thinking I want to reorganize options in the menu. "Game/" has gradually been becoming "Misc"...

We could add an Interface section or something along those lines instead, perhaps?

Comment (Baklap4) [reply game/screen_sing.hh]: That's pretty neat :+1:

Comment (earlye) [reply game/screen_sing.hh]: Seems like you could just use `auto&` rather than being explicit about the type.

File: data/config/schema.xml [hunk 7]
```diff
@@ -75,6 +75,16 @@ to save the current settings to XML.
 		<short>Playlist screen timeout</short>
 		<long>How long it will take before the next song in the playlist starts automatically.</long>
 	</entry>
+	<entry name="game/results_timeout" type="int" value="5">
```
Comment (nieknooijens) [inline data/config/schema.xml]: shouldn't we make a seperate issue for the settings menu? it's becoming pretty cluttered right now, marbe rework the categories?

File: game/menu.cc [hunk 8]
```diff
@@ -15,6 +15,10 @@ std::string MenuOption::getName() const {
 	return "";
 }
 
+std::string MenuOption::getVirtName() const {
+	return !virtualName.empty() ? virtualName : std::string();
```
Comment (nieknooijens) [inline game/menu.cc]: syntax is <statement> ? action on true : action on false.
so `!virtualName.empty() ? virtualName : std::string(); `completely reverses that which seems a little confusing, I'd rather have:

`return virtualName.empty() ? std::string() :  virtualName;`

File: game/menu.hh [hunk 9]
```diff
@@ -29,7 +29,12 @@ public:
 	MenuOption(const std::string& nm, const std::string& comm, MenuImage img = MenuImage());
 
 	/// Make the option change values of a ConfigItem.
-	MenuOption& changer(ConfigItem& val) { type = CHANGE_VALUE; value = &val; return *this; }
+	MenuOption& changer(ConfigItem& val, std::string virtOptName = std::string()) {
+		type = CHANGE_VALUE;
+		value = &val;
+		if (!virtOptName.empty()) virtualName = virtOptName;
```
Comment (nieknooijens) [inline game/menu.hh]: brackets here please { }
so `if (!virtOptName.empty()) { virtualName = virtOptName; }`

this avoids any confusion

File: game/screen_sing.cc [hunk 10]
```diff
@@ -40,6 +38,17 @@ ScreenSing::ScreenSing(std::string const& name, Audio& audio, Database& database
 	m_selectedTrack(TrackName::LEAD_VOCAL)
 {}
 
+bool ScreenSing::singingDuet() {
+	bool sameVoice = true;
+	for (size_t player = 0; player < players(); ++player) {
+		ConfigItem& vocalTrack = m_vocalTracks[player];
+		if (player == 0) selectedVocalTrack = vocalTrack.i();
```
Comment (nieknooijens) [inline game/screen_sing.cc]: same as comment above, brackets please { }

File: game/screen_sing.cc [hunk 11]
```diff
@@ -73,41 +81,49 @@ void ScreenSing::enter() {
 	m_audio.playMusic(m_song->music, false, 0.0, setup_delay);
 	gm->loading(_("Loading menu..."), 0.7);
 	{
+		m_duet = ConfigItem(0);
+		for (size_t player = 0; player < players(); ++player) {
+					ConfigItem& vocalTrack = m_vocalTracks[player];
```
Comment (nieknooijens) [inline game/screen_sing.cc]: what's with this indention?

File: game/screen_sing.cc [hunk 12]
```diff
@@ -256,17 +272,18 @@ void ScreenSing::activateNextScreen()
...
+	Song::Status status = m_song->status(time, singingDuet(), selectedVocalTrack);
 	// When score window is displayed
 	if (m_score_window.get()) {
 		if (nav == input::NAV_START || nav == input::NAV_CANCEL) activateNextScreen();
 		return;  // The rest are only available when score window is not displayed
 	}
 	// Instant quit with CANCEL at the very beginning
 	if (nav == input::NAV_CANCEL && time < 1.0) {
-		Game::getSingletonPtr()->activateScreen("Playlist");
+		if (m_menu.isOpen()) m_menu.moveToLast();
```
Comment (nieknooijens) [inline game/screen_sing.cc]: brackets please {} on both if and else

File: data/config/schema.xml (hunk 7 above)
Comment (Lord-Kamina) [reply data/config/schema.xml]: Yes we should and I'll get on that when I finish this.

**Comment by Lord-Kamina** [comment]
Please try to take a look at the horrible things I'm scheming here.

**Comment by Lord-Kamina** [comment]
Ideally, I'd like to make the logic for deciding whether to shorten or combine a couple of notes smarter (i.e. check for "-" and "~" which are almost always continuations of the previous note, and such) and maybe we could also make these features optional through the settings.

File: game/songparser.cc [hunk 13]
```diff
@@ -290,33 +281,31 @@ void SongParser::finalize() {
...
-					itn = vocal.notes.erase(itn);
-				} else {
-					++itn;
-				}
+			Note::Type type = itn->type;
+			if(type == Note::SLEEP && lastType == Note::SLEEP) {
+				std::clog << "songparser/info: " + m_song.filename.string() + ": Discarding empty sentence" << std::endl;
+				itn = vocal.notes.erase(itn);
+			} else { ++itn; }
 				lastType = type;
```
Comment (nieknooijens) [inline game/songparser.cc]: woah :astonished: more than I asked for. I'm happy now, let me know when it's out of [WIP] then i'll re-review

**Comment by Baklap4** [comment]
Is this still WIP?

**Comment by Lord-Kamina** [comment]
Not really; whatever else I think of later can be done as additional PRs.

**Comment by Baklap4** [comment]
@nieknooijens can you recheck the changes? and hit the button if all is alright? Thankyou!
