### PR TITLE
Fix crash on shader error destroy

### LINKED ISSUE #750: Crash when stoping performous after trying to use 3D
https://user-images.githubusercontent.com/820313/166152661-ebcdbd54-b374-46f5-9663-bb43c64c9e26.mp4

Just activate the 3D on my laptop and exit the game, then it crashes

### PR DESCRIPTION
**Pull request by OznOg**
Fixes #750 

Prevent trying to delete a FBO that was invalidated and report the shader error early when creation fails.

### CODE REVIEW

**Comment by Baklap4** [comment]
I've canceled the pipeline since we've made a breaking change for ubuntu 1804 (pr will open in a bit)

**Comment by OznOg** [comment]
> I've canceled the pipeline since we've made a breaking change for ubuntu 1804 (pr will open in a bit)

Scandal!

File: game/fbo.hh [hunk 1]
```diff
@@ -16,7 +16,8 @@ class FBO {
 	}
 	/// Handle clean-up
 	~FBO() {
-		if (m_fbo) glDeleteFramebuffers(1, &m_fbo);
+            if (glIsFramebuffer(m_fbo) == GL_TRUE)
```
Comment (Baklap4) [inline game/fbo.hh:19]: This can be shortened to `if (glIsFrambuffer(m_fbo)` right?

File: game/menu.cc [hunk 2]
```diff
@@ -61,16 +61,24 @@ void Menu::action(int dir) {
...
 					Game::getSingletonPtr()->setLanguage(value.getValue());
-				}
+				} else if (current().value->getName() == "graphic/stereo3d") {
+					try {
+						std::clog << "video/info: Stereo 3D configuration changed, will reset shaders.\n";
+						Game::getSingletonPtr()->window().resetShaders();
+					} catch (const std::exception &) {
+						std::cerr << "video/info: Disable Stereo 3D because shader creation failed.\n";
+						current().value->b() = false; // Disable 3D if shader fails
+						throw;
```
Comment (Baklap4) [inline game/menu.cc:79]: By rethrowing don't we get a runtime exception?

File: game/fbo.hh (hunk 1 above)
Comment (Lord-Kamina) [reply game/fbo.hh:19]: I don't think `GLBooleans` are implemented as actual bool so no. Unless you want to get ants? Because that's how you get ants.

Comment (OznOg) [reply game/fbo.hh:19]: well Yes and no: hopefully, GL_TRUE is !=0 but who can really say it will always be the case?...

Comment (Baklap4) [reply game/fbo.hh:19]: Fair enough

File: game/menu.cc (hunk 2 above)
Comment (OznOg) [reply game/menu.cc:79]: nop, this is caught from the above exception handler and display an error message on the window

File: game/fbo.hh (hunk 1 above)
Comment (OznOg) [reply game/fbo.hh:19]: that said comparing to TRUE is usually a bad idea

Comment (OznOg) [reply game/fbo.hh]: done

**Comment by Baklap4** [comment]
Hmm while on master: 

- enabling stereoscopic 3d
- Save config
- Something went wrong with the linkin the shader
- Neglecting the error and moving to the songbrowser i do however see the image below clearly indicating that its working

image

With this PR i cannot get stereoscopic 3d to be enabled resulting in never be able to see the songbrowser as above

**Comment by OznOg** [comment]
from discussion on Discord we agreed to integrate @Lord-Kamina 's patch that fixes the shaders' compilation to this PR

**Review by Baklap4 — DISMISSED** [review]
Fixes linked bug. Is there also a bug for the compilation of the shaders? If yes, please link these here aswell so it gets closed

**Comment by OznOg** [comment]
> Hmm while on master:
> 
>     * enabling stereoscopic 3d
> 
>     * Save config
> 
>     * Something went wrong with the linkin the shader
> 
>     * Neglecting the error and moving to the songbrowser i do however see the image below clearly indicating that its working
> 
>     * Quiting the game results into mentioned error in the linked issue
> 
> 
> image
> 
> With this PR i cannot get stereoscopic 3d to be enabled resulting in never be able to see the songbrowser as above

Even if code could "almost work" in case of shader error, I think it is better not to keep half working things going on. Disabling the 3D in case of error is a bit radical, but I think it is the best way to prevent unexpected behaviours and funky bugs. I think we should fix errors in the first place.

**Comment by Baklap4** [comment]
> Even if code could "almost work" in case of shader error, I think it is better not to keep half working things going on. Disabling the 3D in case of error is a bit radical, but I think it is the best way to prevent unexpected behaviours and funky bugs. I think we should fix errors in the first place.

Agreed, but for this there was already a fix at hand, so there was no need to 'break' functionality. But in general yes for sure!
